#General
work dir: 20_tp_sims
slimfile: ../../slimfiles/onePop-selectiveSweep-vcf-noselcoeff.slim
experiment name: 20_Timepoint

mut types: [2]
scenarios: ["neut", "ssv", "sdn"]
win_size: 51

num_sample_points : 20
inds_per_tp : 10  # Diploid inds
physLen : 5000000

sample sizes: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
ploidy: 2

#Simulation
reps: 2500
slim path: slim
