#General
work dir: .
slimfile: ../simple_sims/slimfiles/onePop-selectiveSweep-vcf-noselcoeff.slim 

sample sizes: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
ploidy: 2
win_size: 101

#Simulation
reps: 2500
slim path: slim