#General
work dir: test_bottleneck/
slimfile: bottleneck.slim
slim path: slim

experiment name: Bottleneck
mut types: [2]

scenarios: ["neut", "ssv", "sdn"]

win_size: 51

num_sample_points : 20

inds_per_tp : 10  # Diploid inds

physLen : 5000000

sample sizes: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]

ploidy: 2

reps: 30000