#General
work dir: 40_tp_sims
slimfile: ../../slimfiles/onePop-selectiveSweep-vcf-noselcoeff.slim

mut types: [2]
scenarios: ["neut", "sdn", "ssv"]
win_size: 51

num_sample_points : 40
inds_per_tp : 5  # Diploid inds
physLen : 5000000

sample sizes: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
ploidy: 2

#Simulation
reps: 2500
slim path: slim
