#General
work dir: /pine/scr/l/s/lswhiteh/timesweeper-experiments/misspec/sample_size_10_benchmark/sample_size_10_benchmark_uni_sel
slimfile: ../simple_sims/slimfiles/onePop-selectiveSweep-vcf-noselcoeff.slim 

sample sizes: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
ploidy: 2
win_size: 1

#Simulation
reps: 2500
slim path: slim