#General
work dir: tp_sims
slimfile: ../../slimfiles/onePop-selectiveSweep-vcf-noselcoeff.slim

mut types: [2]
scenarios: ["neut", "sdn", "ssv"]
win_size: 51

#Simulation
num_sample_points : 100
inds_per_tp : 2000  # Diploid inds
physLen : 5000000
reps: 30000
slim path: slim

#Processing and Empirical Data
sample sizes: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
ploidy: 2


