#General
work dir: reg
slimfile: ../simple_sims/slimfiles/onePop-selectiveSweep-vcf-noselcoeff.slim 

mut types: [2]
scenarios: ["neut", "hard", "soft"]

sample sizes: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
ploidy: 2
win_size: 51

#Simulation
reps: 5000
slim path: slim