#General
work dir: tp_sims
slimfile: ../../slimfiles/onePop-selectiveSweep-vcf-noselcoeff.slim

mut types: [2]
scenarios: ["neut", "ssv", "sdn"]
win_size: 51

num_sample_points : 10
inds_per_tp : 20  # Diploid inds
physLen : 5000000

sample sizes: [20, 20, 20, 20, 20, 20, 20, 20, 20, 20]
ploidy: 2

#Simulation
reps: 2500
slim path: slim
