#General
work dir: train_benchmark/
slimfile: /work/users/l/s/lswhiteh/timesweeper-experiments/simple_sims/slimfiles/onePop-selectiveSweep-vcf-noselcoeff.slim
slim path: slim
experiment name: Transformer

mut types: [2]

scenarios: ["neut", "ssv", "sdn"]

win_size: 51

num_sample_points : 20

inds_per_tp : 10  # Diploid inds

physLen : 5000000

sample sizes: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]

ploidy: 2

reps: 10000
