#General
work dir: 2_tp_sims
slimfile: ../../slimfiles/onePop-selectiveSweep-vcf-noselcoeff.slim
experiment name: 2_Timepoint

mut types: [2]
scenarios: ["neut", "ssv", "sdn"]
win_size: 51

num_sample_points : 2
inds_per_tp : 200  # Diploid inds
physLen : 5000000

sample sizes: [100, 100]
ploidy: 2

#Simulation
reps: 2500
slim path: slim
