#General
work dir: win_size_sims/
slimfile: ../../slimfiles/onePop-selectiveSweep-vcf-noselcoeff.slim
slim path: slim


mut types: [2]

scenarios: ["neut", "sdn", "ssv"]

win_size: 3

num_sample_points : 20

inds_per_tp : 1  # Diploid inds

physLen : 5000000

sample sizes: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]

ploidy: 2

reps: 30000
