#General
work dir: sample_size_10_paper
slimfile: ../../slimfiles/onePop-selectiveSweep-vcf-noselcoeff.slim

mut types: [2]
scenarios: ["neut", "sdn", "ssv"]
win_size: 51

num_sample_points : 20
inds_per_tp : 10  # Diploid inds
physLen : 5000000

sample sizes: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
ploidy: 2
gens sampled: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190]

#Simulation
reps: 5000
slim path: slim

