#General
work dir: ./ts_simulans
slim path: slim
ploidy: 2 #Each sample will be multiplied by this value when accessing vcf.
sample sizes: [100, 100, 100, 100, 100, 100, 100] #Number of individual organisms, not chromosomes
seed: 42
experiment name: D_simulans

#Stdpopsim Simulations - Do not need if using simple_simulate
reps: 2500 #Number of replicates for each class
slimfile: d_simulans_model.slim #Base slim script created by stdpopsim
pop: p1 #Integer population identifier, referenced from the demographic model in stdpopsim docs 
mut types: [2]
scenarios: ["neut", "ssv"]
win_size: 51
num_sample_points: 7
