#General
work dir: constant_train/
slimfile: constant_pop.slim
slim path: slim
experiment name: Constant_Pop

mut types: [2]

scenarios: ["neut", "ssv", "sdn"]

win_size: 51

num_sample_points : 20

inds_per_tp : 10  # Diploid inds

physLen : 50000

sample sizes: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]

ploidy: 2

reps: 10000
