#General
work dir: samp_size_sims
slimfile: ../../slimfiles/onePop-selectiveSweep-vcf-noselcoeff.slim
slim path: slim
experiment name: Sample_Size_5


mut types: [2]
scenarios: ["neut", "ssv", "sdn"]
win_size: 51
num_sample_points : 20
inds_per_tp : 5  # Diploid inds
physLen : 5000000

sample sizes: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
ploidy: 2

#Simulation
reps: 2500
