#General
work dir: tp_sims
slimfile: ../../slimfiles/onePop-selectiveSweep-vcf-noselcoeff.slim

mut types: [2]
scenarios: ["neut", "sdn", "ssv"]
win_size: 51

num_sample_points : 5
inds_per_tp : 40  # Diploid inds
physLen : 5000000

sample sizes: [40, 40, 40, 40, 40]
ploidy: 2

#Simulation
reps: 2500
slim path: slim
