#General
work dir: 0.1_selcoeff
slimfile: onePop-selectiveSweep-s0.1.slim
slim path: slim
experiment name: Sel_Coeff_0.10


mut types: [2]
scenarios: ["neut", "ssv", "sdn"]
win_size: 51
num_sample_points : 20
inds_per_tp : 10  # Diploid inds
physLen : 5000000

sample sizes: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
ploidy: 2

#Simulation
reps: 30000
